#!/usr/bin/env bash

file=$1
source=$2
#commit_sha=$3

#exit if source == 'commit'
if [ "${source}" == "commit" ]; then
  exit 0
fi

path=$(git symbolic-ref HEAD)
if [ $? -ne 0 ]; then
  exit 0
fi

current=${path#refs/heads/}

jiras=$(git config --get-all "branch.${current}.jira-ticket" | sort -u)
if [ $? -eq 0 ]; then
  smart_commit=""
  for jira_id in $jiras; do
    smart_commit+="$jira_id "
  done
  awk "/^#/ && !x {print \"$smart_commit\"; x=1} 1" "$file" > "$file.tmp"
  mv "$file.tmp" "$file"
fi
